theme = "cyberpunk-pink"

[editor]
line-number = "relative"
mouse = true
auto-completion = true
completion-trigger-len = 2
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true
display-inlay-hints = true
